name: ma-mag

networks:
  gateway-net:
    name: gateway-net
  message-net:
    name: message-net

include:
  - ./services/logging/docker-compose.yml
  - ./services/auth-service/docker-compose.yml
  - ./services/order-service/docker-compose.yml
  - ./services/notification-service/docker-compose.yml

services:
  api-gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - gateway-net
    depends_on:
      - auth-proxy
      - order-proxy
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
        tag: "api-gateway"

  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    networks:
      - message-net
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
        tag: "rabbitmq"
