name: ma-mag

networks:
  gateway-net:
    name: gateway-net
  message-net:
    name: message-net
  db-pgadmin-net:
    name: db-pgadmin-net

include:
  - ./services/logging/docker-compose.yml
  - ./services/auth/docker-compose.yml
  - ./services/order/docker-compose.yml
  - ./services/notification/docker-compose.yml

services:
  api-gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - gateway-net
    depends_on:
      - auth-proxy
      - order-proxy

  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    networks:
      - message-net

  pgadmin:
    image: dpage/pgadmin4:9.18
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
      - PGADMIN_CONFIG_SERVER_MODE=True
    volumes:
      - auth_pgadmin_data:/var/lib/pgadmin
    networks:
      - db-pgadmin-net
    restart: unless-stopped
    ports:
      - "5050:80"
    depends_on:
      auth-db:
        condition: service_healthy

volumes:
  auth_pgadmin_data:
