input {
  tcp {
    port => 50000
    codec => json_lines
    type => "docker"
  }
}

filter {
  if [message] =~ /^\{.*\}$/ {
    json {
      source => "message"
      skip_on_invalid_json => true
    }
  }

  if [tag] {
    mutate {
      add_field => { "container.name" => "%{tag}" }
    }
  }

  mutate {
    coerce => {
      "service.environment" => "development"
      "log.level" => "INFO"
    }
  }

  mutate {
    gsub => [
      "message", "password=[^&]*", "password=***",
      "message", "RABBITMQ_PASS=[^ ]*", "RABBITMQ_PASS=***"
    ]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "microservices-logs-%{+YYYY.MM.dd}"
  }
}
