services:
  order-proxy:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - gateway-net
      - order-internal
    depends_on:
      - order-api
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
        tag: "order-proxy"

  order-api:
    build: .
    environment:
      - SERVICE_NAME=order-service
      - ROOT_PATH=/api/orders
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_PASS=${RABBITMQ_DEFAULT_PASS}
    networks:
      - order-internal
      - message-net
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
        tag: "order-api"

networks:
  gateway-net:
    name: gateway-net
  order-internal:
    internal: true
  message-net:
    name: message-net
